// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAInfUd-bVk6cQw0bqlfa_nPHlVBOR3d3w',
    appId: '1:892775201186:web:1634005f124413b684dafb',
    messagingSenderId: '892775201186',
    projectId: 'rivr-official',
    authDomain: 'rivr-official.firebaseapp.com',
    storageBucket: 'rivr-official.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFj01yP4GDCoFzJrMwiwqld7fFYy7hvKU',
    appId: '1:892775201186:android:199bb3c2b8ab33d584dafb',
    messagingSenderId: '892775201186',
    projectId: 'rivr-official',
    storageBucket: 'rivr-official.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcGnjMqxFqo0-uQ7mj2TkMaEqK-CX8nwQ',
    appId: '1:892775201186:ios:31cc57368732dfd584dafb',
    messagingSenderId: '892775201186',
    projectId: 'rivr-official',
    storageBucket: 'rivr-official.firebasestorage.app',
    iosBundleId: 'com.byuhydroinformaticslab.rivr',
  );
}
